### ISSUE TITLE
My Twilio Dev Number is failing to start ❓ 

### ISSUE THREAD

**Issue by Valvalvaal** [twilio-labs/dev-phone#157]
This is the output that I'm getting when I try to start my Twilio Dev Phone. I logged in before running twilio dev-phone but the Dev Phone won't start, I'm copying the debug output as indicated.

````
➜  ~ twilio dev-phone -l debug
[DEBUG] Config File: /Users/valeria/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
Hello 👋 I'm your dev-phone and my name is dev-phone-9825

[DEBUG] Found command "dev-phone" plugin: @twilio-labs/plugin-dev-phone
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/dev-phone/issues"
[DEBUG] accountSid must start with AC
[DEBUG] Error: accountSid must start with AC
    at new Twilio (/Users/valeria/.twilio-cli/node_modules/twilio/lib/rest/Twilio.js:148:11)
    at new initializer (/Users/valeria/.twilio-cli/node_modules/twilio/lib/index.js:10:10)
    at DevPhoneServer.buildClient (/Users/valeria/.twilio-cli/node_modules/@twilio/cli-core/src/base-commands/twilio-client-command.js:138:12)
    at get twilioClient [as twilioClient] (/Users/valeria/.twilio-cli/node_modules/@twilio/cli-core/src/base-commands/twilio-client-command.js:125:26)
    at DevPhoneServer.<anonymous> (/Users/valeria/.twilio-cli/node_modules/@twilio-labs/plugin-dev-phone/dist/commands/dev-phone.js:65:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/valeria/.twilio-cli/node_modules/@twilio-labs/plugin-dev-phone/dist/commands/dev-phone.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ayyrickay** [comment]
@Valvalvaal it seems like the profile is maybe set up incorrectly? It seems like a strange value is being used for the account sid. Out of curiosity, which version of the CLI are you using?
