### ISSUE TITLE
Services are limited to less than or equal to 50 

### ISSUE THREAD

**Issue by NeizKap** [twilio-labs/dev-phone#178]
This is the output that I'm getting when I try to start Twilio Dev Phone. It's not running
My node version is v16.14.0

```
PS C:\MyData\Projects\JobProjects\backend> twilio dev-phone -l debug  
[DEBUG] Config File: C:\Users\OneIvan\.twilio-cli\config.json
[DEBUG] Using profile: OneIvan
Hello 👋 I'm your dev-phone and my name is dev-phone-1260

✅ I'm using your profile API key.

[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://conversations.twilio.com/v1/Services
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:37 GMT","content-type":"application/json; charset=utf-8","content-length":"11089","connection":"close","twilio-request-id":"RQ98e32b70bf6da3c45bc7234d499d737c","twilio-request-duration":"0.033","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
🚮 Removing existing dev phone Conversation Services
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] DELETE https://conversations.twilio.com/v1/Services/ISa322c70cfe1f4e74b384c9e180c8e64a
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
💻 Creating a new conversation...
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://conversations.twilio.com/v1/Services
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 204
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:37 GMT","content-type":"application/json; charset=utf-8","connection":"close","twilio-request-id":"RQba0f2a47044e3e9075fa34c16be9bc56","twilio-request-duration":"0.070","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}     
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:38 GMT","content-type":"application/json; charset=utf-8","content-length":"942","connection":"close","twilio-request-id":"RQc64823ff3f83bc7479c3490949e0522d","twilio-request-duration":"0.042","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://conversations.twilio.com/v1/Services/ISd22b25218e8b419aa58472a39b3373e8/Conversations
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone-1260
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:38 GMT","content-type":"application/json; charset=utf-8","content-length":"1043","connection":"close","twilio-request-id":"RQc4bb8facbfce2303077397abb3c8420a","twilio-request-duration":"0.265","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://conversations.twilio.com/v1/Services/ISd22b25218e8b419aa58472a39b3373e8/Conversations/CH683daa1047854db08930d0c5a49206d6/Participants
[DEBUG] Form data:
[DEBUG] Identity=dev-phone-1260
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:39 GMT","content-type":"application/json; charset=utf-8","content-length":"670","connection":"close","twilio-request-id":"RQd79d389a1f4cb52c0fbafd70b2b9bceb","twilio-request-duration":"0.461","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
✅ I'm using the conversation CH683daa1047854db08930d0c5a49206d6 from servic
e ISd22b25218e8b419aa58472a39b3373e8

💻 Creating a new sync list for call history...
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://sync.twilio.com/v1/Services
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:40 GMT","content-type":"application/json; charset=utf-8","content-length":"2060","connection":"close","twilio-request-id":"RQ002b9ebe95f3fa7ea2d747c6563b15fa","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
🚮 Removing existing dev phone Sync Services
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] DELETE https://sync.twilio.com/v1/Services/IS9e1df5c92a9fc3aa1d87f023a92e457e
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://sync.twilio.com/v1/Services
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone-1260
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 204
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:41 GMT","content-type":"application/json; charset=utf-8","connection":"close","twilio-request-id":"RQ63492498c614d5b4fd7b829b17a7dbed","twilio-request-duration":"0.056","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:41 GMT","content-type":"application/json; charset=utf-8","content-length":"894","connection":"close","twilio-request-id":"RQ30fa615f999dec4eaa3bad8c74b04f06","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
✅ I'm using the sync service ISc75ccff119b46e9c898868feace1bfe0

[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://sync.twilio.com/v1/Services/ISc75ccff119b46e9c898868feace1bfe0/Maps
[DEBUG] Form data:
[DEBUG] UniqueName=CallLog
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.12.0 @twilio/cli-core/7.6.0 (win32 ia32) twilio-node/3.84.1 node/v18.17.0 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Wed, 16 Aug 2023 12:33:42 GMT","content-type":"application/json; charset=utf-8","content-length":"722","connection":"close","twilio-request-id":"RQb4a2c604351343486a4380eb275b63e8","twilio-request-duration":"0.032","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","strict-transport-security":"max-age=31536000","twilio-concurrent-requests":"1","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
💻 Deploying a Functions Service to handle incoming calls and SMS...       
🧑‍💻 Creating Service
ClientApiError [TwilioApiError]: Services are limited to less than or equal to 50
    at convertApiErrorsAndThrow (C:\Users\Иван\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\utils\error.js:33:15)
    at TwilioServerlessApiClient.<anonymous> (C:\Users\Иван\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\client.js:515:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Иван\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\client.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 20001,
  url: 'https://serverless.twilio.com/v1/Services',
  details: {
    code: 20001,
    message: 'Services are limited to less than or equal to 50',
    more_info: 'https://www.twilio.com/docs/errors/20001',
    status: 400
  }
}
[DEBUG] Found command "dev-phone" plugin: @twilio-labs/plugin-dev-phone    
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/dev-phone/issues"
[DEBUG] Issue deploying functions. Try again later
[DEBUG] Error: Issue deploying functions. Try again later
    at C:\Users\Иван\.twilio-cli\node_modules\@twilio-labs\plugin-dev-phone\dist\utils\create-serverless-util.js:82:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Иван\.twilio-cli\node_modules\@twilio-labs\plugin-dev-phone\dist\utils\create-serverless-util.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 »   Error: EEXIT: 1
 »   Code: EEXIT
```

**Comment by ayyrickay** [comment]
@NeizKap Can you check your functions services in the Twilio Console? Should be here: https://console.twilio.com/us1/develop/functions/services

You should be able to delete services if you've hit the limit!
