### ISSUE TITLE
Services are limited to less than or equal to 50

### ISSUE THREAD

**Issue by var1ap-WA** [twilio-labs/dev-phone#194]
I cannot start dev phone anymore, please investigate
`twilio-cli/5.17.0 win32-x86 node-v18.18.2`

```
twilio dev-phone -l debug
[DEBUG] Config File: C:\Users\varyu\.twilio-cli\config.json
[DEBUG] Using profile: var1ap
Hello 👋 I'm your dev-phone and my name is dev-phone-7394

✅ I'm using your profile API key.

services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] get https://conversations.twilio.com/v1/Services
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:08 GMT","content-type":"application/json; charset=utf-8","content-length":"2188","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQ8e8d3a5cd572fcc3ca8b18500905fe79","twilio-request-duration":"0.025","twilio-concurrent-requests":"1","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
🚮 Removing existing dev phone Conversation Services
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] delete https://conversations.twilio.com/v1/Services/ISa90b4702735c4c58989cc8fc30795007
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
💻 Creating a new conversation...
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://conversations.twilio.com/v1/Services
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 204
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:08 GMT","content-type":"application/json; charset=utf-8","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQ66b554a29abf898b782e7ad292e1456c","twilio-request-duration":"0.047","twilio-concurrent-requests":"2","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:08 GMT","content-type":"application/json; charset=utf-8","content-length":"942","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQ81c2d92016b6c0744c129caa28a232c6","twilio-request-duration":"0.056","twilio-concurrent-requests":"1","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://conversations.twilio.com/v1/Services/IS8004e54e42a3429e8f2ee0cbb198e007/Conversations
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone-7394
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:09 GMT","content-type":"application/json; charset=utf-8","content-length":"1043","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQ24cbc3801721156741f6174788d384fd","twilio-request-duration":"0.234","twilio-concurrent-requests":"1","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://conversations.twilio.com/v1/Services/IS8004e54e42a3429e8f2ee0cbb198e007/Conversations/CH0866c9c2e1c94c639f7156f8859df8f0/Participants
[DEBUG] Form data:
[DEBUG] Identity=dev-phone-7394
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:10 GMT","content-type":"application/json; charset=utf-8","content-length":"670","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQ996833b60a2172d544723773030df486","twilio-request-duration":"0.364","twilio-concurrent-requests":"1","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"conversations.twilio.com"}
✅ I'm using the conversation CH0866c9c2e1c94c639f7156f8859df8f0 from service IS8004e54e42a3429e8f2ee0cbb198e007

💻 Creating a new sync list for call history...
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] get https://sync.twilio.com/v1/Services
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:10 GMT","content-type":"application/json; charset=utf-8","content-length":"2060","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQdfea9c30a036642e96ca4f55fc035cfb","twilio-request-duration":"0.016","twilio-concurrent-requests":"1","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
🚮 Removing existing dev phone Sync Services
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] delete https://sync.twilio.com/v1/Services/IS0f53abc97599c46a5807939f15a338bb
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://sync.twilio.com/v1/Services
[DEBUG] Form data:
[DEBUG] FriendlyName=dev-phone-7394
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:11 GMT","content-type":"application/json; charset=utf-8","content-length":"894","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQbfb78a10aadf9e2c5a1095fd4041b4a4","twilio-request-duration":"0.019","twilio-concurrent-requests":"2","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
✅ I'm using the sync service IS99b334f3496167af170fdfa41ee9b0c8

services is deprecated. Use v1.services instead.
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://sync.twilio.com/v1/Services/IS99b334f3496167af170fdfa41ee9b0c8/Maps
[DEBUG] Form data:
[DEBUG] UniqueName=CallLog
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/5.17.0 @twilio/cli-core/7.19.1 (win32 ia32) twilio-node/4.20.1 node/v18.18.2 dev-phone
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 204
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:11 GMT","content-type":"application/json; charset=utf-8","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQa0ecaf80ca8ed92f8f2dc4997582cc9a","twilio-request-duration":"0.031","twilio-concurrent-requests":"1","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Mon, 22 Jan 2024 08:36:11 GMT","content-type":"application/json; charset=utf-8","content-length":"722","connection":"close","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","twilio-request-id":"RQa7e94322a042089999873c6ec6e8a3ef","twilio-request-duration":"0.034","twilio-concurrent-requests":"1","x-verification-disclosure":"Message Accepted. Pending content verification for US/Canada destination numbers:","x-shenanigans":"none","x-powered-by":"AT-5000","x-home-region":"us1","x-api-domain":"sync.twilio.com"}
💻 Deploying a Functions Service to handle incoming calls and SMS...
🧑‍💻 Creating Service
ClientApiError [TwilioApiError]: Services are limited to less than or equal to 50
    at convertApiErrorsAndThrow (C:\Users\varyu\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\utils\error.js:33:15)
    at TwilioServerlessApiClient.<anonymous> (C:\Users\varyu\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\client.js:515:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\varyu\.twilio-cli\node_modules\@twilio-labs\serverless-api\dist\client.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 20001,
  url: 'https://serverless.twilio.com/v1/Services',
  details: {
    code: 20001,
    message: 'Services are limited to less than or equal to 50',
    more_info: 'https://www.twilio.com/docs/errors/20001',
    status: 400
  }
}
[DEBUG] Found command "dev-phone" plugin: @twilio-labs/plugin-dev-phone
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/dev-phone/issues"
[DEBUG] Issue deploying functions. Try again later
[DEBUG] Error: Issue deploying functions. Try again later
    at C:\Users\varyu\.twilio-cli\node_modules\@twilio-labs\plugin-dev-phone\dist\utils\create-serverless-util.js:82:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\varyu\.twilio-cli\node_modules\@twilio-labs\plugin-dev-phone\dist\utils\create-serverless-util.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 »   Error: EEXIT: 1
 »   Code: EEXIT
```

**Comment by var1ap-WA** [comment]
![image](https://github.com/twilio-labs/dev-phone/assets/63446336/fb965a28-9d96-486f-a017-03e85746f4c6)
Hey @ayyrickay, I've found your answer [here](https://github.com/twilio-labs/dev-phone/issues/190) to delete some services, but it's not looks like not possible

**Comment by var1ap-WA** [comment]
How to delete service (helps with dev phone issue)
[Services | Twilio](https://console.twilio.com/us1/develop/functions/services) 



run in console this
`twilio api:serverless:v1:services:remove --sid [SID]`

**Comment by ayyrickay** [comment]
> How to delete service (helps with dev phone issue) [Services | Twilio](https://console.twilio.com/us1/develop/functions/services)
> 
> run in console this `twilio api:serverless:v1:services:remove --sid [SID]`

Thanks for following up on this. That looks correct. If I recall correctly, services created via API must be interacted with via API - they're read-only in the console. That appears to extend to deleting. Glad you reached a solution!
